// ─── Balance Scalars ──────────────────────────────────────────────────────────
// Per-matchup (1v1) and per-build (FFA) damage scalars for combat fairness.
// Generated by tuning scripts in scripts/. Re-run to update.
//
// In 1v1: look up "attackerBuild_defenderBuild" to get the scalar.
// In FFA: look up "build" to get the scalar.
// Scalar is applied to raw damage: finalDamage = max(1, round(rawDamage * scalar))

/**
 * Generates a build key from star values: "D-A-S"
 */
export function buildKey(stars: { damage: number; accuracy: number; speed: number }): string {
  return `${stars.damage}-${stars.accuracy}-${stars.speed}`
}

/**
 * Generates a matchup key for 1v1 scalar lookup.
 * Format: "attackerBuild_defenderBuild"
 */
export function matchupKey(
  attacker: { damage: number; accuracy: number; speed: number },
  defender: { damage: number; accuracy: number; speed: number }
): string {
  return `${buildKey(attacker)}_${buildKey(defender)}`
}

// ─── 1v1 Per-Matchup Corrections ─────────────────────────────────────────────
// 756 entries (378 pairs x 2 directions).
// Generated by: npx tsx packages/server/src/games/battle-bots/scripts/tune1v1Matchups.ts
// Current precision: all 378 pairs within +/-1% of 50% win rate.
// TODO: Re-run tune1v1Refine.ts to tighten remaining ~54 pairs to +/-0.5%.
//
// When a key is missing, scalar defaults to 1.0 (no correction).
export const MATCHUP_1V1_SCALARS: Record<string, number> = {
  // Placeholder — will be populated by running tune1v1Matchups.ts and pasting output.
  // For now, all matchups use 1.0 (no correction, raw Table E5 values only).
  // Raw balance is within +/-5% for all extreme matchups with Table E5.
}

/**
 * Look up the 1v1 damage scalar for an attacker vs a defender.
 * Returns 1.0 if no correction exists for this matchup.
 */
export function get1v1Scalar(
  attacker: { damage: number; accuracy: number; speed: number },
  defender: { damage: number; accuracy: number; speed: number }
): number {
  const key = matchupKey(attacker, defender)
  return MATCHUP_1V1_SCALARS[key] ?? 1.0
}

// ─── FFA Per-Build Corrections ────────────────────────────────────────────────
// 28 entries (one per build).
// Generated by: npx tsx packages/server/src/games/battle-bots/scripts/tuneFFAScalars.ts
// Validated at 5M matches: all builds within +/-0.5% of 25% win rate.
export const FFA_BUILD_SCALARS: Record<string, number> = {
  "6-2-1": 1.1343,
  "7-1-1": 1.1296,
  "6-1-2": 1.1074,
  "5-1-3": 1.0834,
  "5-2-2": 1.0788,
  "5-3-1": 1.0727,
  "4-2-3": 1.0443,
  "4-4-1": 1.0281,
  "4-3-2": 1.0239,
  "1-7-1": 1.0000,
  "2-6-1": 1.0000,
  "3-3-3": 1.0000,
  "4-1-4": 1.0000,
  "2-1-6": 0.9687,
  "3-5-1": 0.9678,
  "3-2-4": 0.9662,
  "3-4-2": 0.9639,
  "2-4-3": 0.9612,
  "2-2-5": 0.9589,
  "1-1-7": 0.9589,
  "3-1-5": 0.9583,
  "2-5-2": 0.9555,
  "2-3-4": 0.9534,
  "1-2-6": 0.9436,
  "1-5-3": 0.9417,
  "1-6-2": 0.9391,
  "1-3-5": 0.9214,
  "1-4-4": 0.9079,
}

/**
 * Look up the FFA damage scalar for a build.
 * Returns 1.0 if no correction exists.
 */
export function getFFAScalar(stars: { damage: number; accuracy: number; speed: number }): number {
  const key = buildKey(stars)
  return FFA_BUILD_SCALARS[key] ?? 1.0
}
